### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [howell33/name-of-my-new-github-repo#1]
:+1: This looks good. If you'd like help getting caught up on these projects, please don't hesitate to let me know. I'm happy to answer as many questions as you may have via email and also happy to meet with you outside of class for individual time if it would be helpful.
### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, just let me know and I'll be happy to point you in the right direction.

**Comment by howell33** [comment]
Hey,

I definitely think meeting would be best. Are you free after 2 tomorrow by
any chance?

Thank You,

_Alicia Howell_
Media and Information
Information Technology l Michigan State University'15
Community Service Chair l African American Student Mentoring Program
President l Delta Sigma Theta Sorority, Inc., Epsilon Epsilon Chapter
howell33@msu.edu l 313-970-6052
